# fly.toml app configuration file generated for jp-dixon-notes on 2023-07-07T18:20:23-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jp-dixon-notes"
primary_region = "gdl"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
