POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRyanA5OSIsImlkIjoiNjRhZDkxOTkxNzM0YjE1MTRlYjg5MzRhIiwiaWF0IjoxNjg5NDA0NTcxfQ.9h-beeUX4-DY_y8nGlDUy_vsK5T1Htg3GX3eQoNBQyE

{
    "title": "Testing out a new thing with tokens...",
    "author": "JP Dixon",
    "url": "some.url.com/token",
    "likes": 1
}