PUT http://localhost:3003/api/blogs/64acbe121223f0ee8b9b9dd2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0YWNiYTVmNDBmZmVlY2YwNGExYTY0YSIsImlhdCI6MTY4OTA0NTE1MSwiZXhwIjoxNjg5MDQ4NzUxfQ.jwNAO8_UElXv-OdK_sqXiZwC9B8PVE1E-YrL3jhtkdU

{
    "title": "Modified blog post~!",
    "author": "JP Dixon",
    "url": "http://www.jp-dixon.com/blog",
    "likes": 7
}